### ISSUE TITLE
Cli rename 

### ISSUE THREAD

**Issue by hansschenker** [ngneat/scam#10]
ng g @ngneat/scam:component --name=navbar --**inline-style** --**inline-template**

**Comment by NetanelBasal** [comment]
?

**Comment by hansschenker** [comment]
Hi Netanel,

I got the message from cli for the command:
ng g @ngneat/scam:component --name=navbar --inlineStyle --inlineTemplate

*cli message:     use: --inline-style --inline-template*

with a test again today I did not get the message again.

Thank's a lot for providing this helpful schematics.
Question: Do you have a blog article where you describe the pros for
applying Angular Scam?

Many thanks and best regards
Hans
calling from Switzerland

**Comment by NetanelBasal** [comment]
Not yet.
