### ISSUE TITLE
ngModule naming convention

### ISSUE THREAD

**Issue by wizardnet972** [ngneat/scam#11]
@NetanelBasal, This is great tooling. Thank you for creating this.

Can you please generate the ngModule name without "component" keyword?

From:
```
export class AppShellComponent implements OnInit { ... }
export class AppShellComponentModule {}
```

To:
```
export class AppShellComponent implements OnInit { ... }
export class AppShellModule {} // <-------
```

**Comment by NetanelBasal** [comment]
No. This is how we differentiate between normal modules to a component module.
