### ISSUE TITLE
Discussion: Do you use this pattern only in libraries?

### ISSUE THREAD

**Issue by loxy** [ngneat/scam#15]
Hi together,

I'm a fan of this pattern (Single Component Angular Module) and use it mainly in applications. Like describes here: https://medium.com/marmicode/your-angular-module-is-a-scam-b4136ca3917b

What do you think? Do you use it only in libraries (where it is applied nearly everywhere) or also in applications?

Best regards,
Kersten

**Comment by shaharkazaz** [comment]
Hey 👋 

I use it widely within applications.

**Comment by NetanelBasal** [comment]
Same
