### ISSUE TITLE
Suggestions about component options

### ISSUE THREAD

**Issue by edbzn** [ngneat/scam#2]
Hi, 

It's a good initiative, schematics for scams was really missing. I also use scams every day and I created my vscode snippets instead of schematics (quick win). In order to replace my snippets with these schematics, I have some suggestions that I would love to see implemented.

- The ability to inline template and style in the component (because I'm also convinced by the single file Angular component),
- the ability to set the `changeDetection` to `OnPush`, on my side it's by default.

**Comment by NetanelBasal** [comment]
You can use every option from the default Angular schematics: 

`ng g @ngneat/scam:component --name=bar --inlineStyle --inlineTemplate`

**Comment by NetanelBasal** [comment]
You can also define default values in `angular.json`:

```json
"schematics": {
   "@ngneat/scam:component": {
     "changeDetection": "OnPush"
   }
}
```

**Comment by edbzn** [comment]
Good! Maybe it should be documented then, thank you.

**Comment by NetanelBasal** [comment]
Updated the docs. Thanks
