### ISSUE TITLE
Module naming

### ISSUE THREAD

**Issue by jits** [ngneat/scam#4]
Hi – thanks for this neat (😄 ) tool.

I notice the naming of the module doesn't include the word `Component` when generating a single component. Is this intentional? If so, could it be made configurable?

As an example:

Generating a singe component file for `profile` will **currently** give:
- `ProfileComponent` 
- `ProfileModule`

I (personally) would prefer it generate:
- `ProfileComponent`
- `ProfileComponentModule`

Let me know your thoughts, and I can submit a PR for this.

**Comment by NetanelBasal** [comment]
Sure, let's add it

**Comment by jits** [comment]
> Sure, let's add it

👍🏽  configurable option, or change the default? (I'd prefer changing the default as I think it makes more sense).

**Comment by NetanelBasal** [comment]
Yeap
