### ISSUE TITLE
Path "" does not exist error when trying to use schematic

### ISSUE THREAD

**Issue by kingjordan** [ngneat/scam#6]
Hello,

I have an angular 11 app and I am trying to use the SCAM schematic to generate a component but I am getting a
Path "" does not exist error.

Details below
```
> Executing task: ng generate @ngneat/scam:component --name=discover-pools --project=myapp--module=pools --style=scss --changeDetection=OnPush --export --path=src/app/features/pools --viewEncapsulation=None --no-interactive <

Option "entryComponent" is deprecated: Since version 9.0.0 with Ivy, entryComponents is no longer necessary.
Path "/.../src/app/features/pools/discover-pools/discover-pools.component.ts" does not exist.
```

the first part of the path does exist: **_/.../src/app/features/pools/_**
however the **_discover-pools/discover-pools.component.ts_** is the file to be created by the schematic, so of course it does not exist.

Am I missing something here?  Can someone help me figure out if I have the cli command wrong or if there is an issue with the schematic.

**Comment by NetanelBasal** [comment]
Fixed in v2.1.0
