### ISSUE TITLE
`Path ... does not exist` error on Windows

### ISSUE THREAD

**Issue by omrumbakitemiz** [ngneat/scam#8]
When I run this command 
`npx ng g @ngneat/scam:component new-password `, I get the following error. 
`Path "/C:/src/app/new-password/new-password.component.ts" does not exist.`

![image](https://user-images.githubusercontent.com/12871066/120817015-fb12b300-c559-11eb-957c-0a1d70666311.png)

I am using PowerShell 7.1.3

### Package versions
@ngneat/scam: 2.0.1
@angular/core: 12.0.2
@angular/cli: 12.0.2

**Comment by NetanelBasal** [comment]
Fixed in v2.1.0
